// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="asi_metadataType")]
[System.Xml.Serialization.XmlRootAttribute("asi_metadata", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="asi_metadataType")]
public partial class Asi_metadataType
{
    
    #region Private fields
    private VocabularyType _vocabulary;
    
    private List<Asi_metadatafieldType> _asi_metadatafield;
    #endregion
    
    public Asi_metadataType()
    {
        this._asi_metadatafield = new List<Asi_metadatafieldType>();
        this._vocabulary = new VocabularyType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("vocabulary")]
    public VocabularyType Vocabulary
    {
        get
        {
            return this._vocabulary;
        }
        set
        {
            this._vocabulary = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("asi_metadatafield", ElementName="asi_metadatafield")]
    public List<Asi_metadatafieldType> Asi_metadatafield
    {
        get
        {
            return this._asi_metadatafield;
        }
        set
        {
            this._asi_metadatafield = value;
        }
    }
}
}
#pragma warning restore
