// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="asi_metadatafieldType")]
[System.Xml.Serialization.XmlRootAttribute("asi_metadatafield", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="asi_metadatafieldType")]
public partial class Asi_metadatafieldType
{
    
    #region Private fields
    private string _field_name;
    
    private string _field_value;
    
    private string _lang;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute("field_name")]
    public string Field_name
    {
        get
        {
            return this._field_name;
        }
        set
        {
            this._field_name = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("field_value")]
    public string Field_value
    {
        get
        {
            return this._field_value;
        }
        set
        {
            this._field_value = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
    public string Lang
    {
        get
        {
            return this._lang;
        }
        set
        {
            this._lang = value;
        }
    }
}
}
#pragma warning restore
