// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="contextType")]
[System.Xml.Serialization.XmlRootAttribute("context", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="contextType")]
public partial class ContextType
{
    
    #region Private fields
    private Qti_commentType _qti_comment;
    
    private string _name;
    
    private List<Generic_identifierType> _generic_identifier;
    
    private List<DateType> _date;
    
    private System.Xml.XmlElement _extension_context;
    #endregion
    
    public ContextType()
    {
        this._date = new List<DateType>();
        this._generic_identifier = new List<Generic_identifierType>();
        this._qti_comment = new Qti_commentType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("qti_comment")]
    public Qti_commentType Qti_comment
    {
        get
        {
            return this._qti_comment;
        }
        set
        {
            this._qti_comment = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public string Name
    {
        get
        {
            return this._name;
        }
        set
        {
            this._name = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("generic_identifier", ElementName="generic_identifier")]
    public List<Generic_identifierType> Generic_identifier
    {
        get
        {
            return this._generic_identifier;
        }
        set
        {
            this._generic_identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("date", ElementName="date")]
    public List<DateType> Date
    {
        get
        {
            return this._date;
        }
        set
        {
            this._date = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute(Name="extension_context", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2")]
    public System.Xml.XmlElement Extension_context
    {
        get
        {
            return this._extension_context;
        }
        set
        {
            this._extension_context = value;
        }
    }
}
}
#pragma warning restore
