// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="controlType")]
[System.Xml.Serialization.XmlRootAttribute("control", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="controlType")]
public partial class ControlType
{
    
    #region Private fields
    private ControlTypeHint_switch _hint_switch;
    
    private ControlTypeSolution_switch _solution_switch;
    
    private ControlTypeFeedback_switch _feedback_switch;
    
    private string _value;
    #endregion
    
    public ControlType()
    {
        this._hint_switch = ControlTypeHint_switch.No;
        this._solution_switch = ControlTypeSolution_switch.No;
        this._feedback_switch = ControlTypeFeedback_switch.No;
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="hint_switch")]
    [System.ComponentModel.DefaultValueAttribute(ControlTypeHint_switch.No)]
    public ControlTypeHint_switch Hint_switch
    {
        get
        {
            return this._hint_switch;
        }
        set
        {
            this._hint_switch = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="solution_switch")]
    [System.ComponentModel.DefaultValueAttribute(ControlTypeSolution_switch.No)]
    public ControlTypeSolution_switch Solution_switch
    {
        get
        {
            return this._solution_switch;
        }
        set
        {
            this._solution_switch = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="feedback_switch")]
    [System.ComponentModel.DefaultValueAttribute(ControlTypeFeedback_switch.No)]
    public ControlTypeFeedback_switch Feedback_switch
    {
        get
        {
            return this._feedback_switch;
        }
        set
        {
            this._feedback_switch = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
