// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="itemfeedbackTypeView")]
[System.Xml.Serialization.XmlRootAttribute("itemfeedbackTypeView")]
public enum ItemfeedbackTypeView
{
    
    /// <remarks/>
    All,
    
    /// <remarks/>
    Administrator,
    
    /// <remarks/>
    AdminAuthority,
    
    /// <remarks/>
    Assessor,
    
    /// <remarks/>
    Author,
    
    /// <remarks/>
    Candidate,
    
    /// <remarks/>
    InvigilatorProctor,
    
    /// <remarks/>
    Psychometrician,
    
    /// <remarks/>
    Scorer,
    
    /// <remarks/>
    Tutor,
}
}
#pragma warning restore
