// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="mattextType")]
[System.Xml.Serialization.XmlRootAttribute("mattext", Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", IsNullable=false, ElementName="mattextType")]
public partial class MattextType
{
    
    #region Private fields
    private string _texttype;
    
    private string _label;
    
    private string _charset;
    
    private string _uri;
    
    private string _entityref;
    
    private string _height;
    
    private string _width;
    
    private string _lang;
    
    private string _value;
    #endregion
    
    public MattextType()
    {
        this._texttype = "text/plain";
        this._charset = "ascii-us";
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="texttype")]
    [System.ComponentModel.DefaultValueAttribute("text/plain")]
    public string Texttype
    {
        get
        {
            return this._texttype;
        }
        set
        {
            this._texttype = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="label")]
    public string Label
    {
        get
        {
            return this._label;
        }
        set
        {
            this._label = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="charset")]
    [System.ComponentModel.DefaultValueAttribute("ascii-us")]
    public string Charset
    {
        get
        {
            return this._charset;
        }
        set
        {
            this._charset = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="uri")]
    public string Uri
    {
        get
        {
            return this._uri;
        }
        set
        {
            this._uri = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ENTITY", AttributeName="entityref")]
    public string Entityref
    {
        get
        {
            return this._entityref;
        }
        set
        {
            this._entityref = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="height")]
    public string Height
    {
        get
        {
            return this._height;
        }
        set
        {
            this._height = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="width")]
    public string Width
    {
        get
        {
            return this._width;
        }
        set
        {
            this._width = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
    public string Lang
    {
        get
        {
            return this._lang;
        }
        set
        {
            this._lang = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
