// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="objectivesType")]
[System.Xml.Serialization.XmlRootAttribute("objectives", Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", IsNullable=false, ElementName="objectivesType")]
public partial class ObjectivesType
{
    
    #region Private fields
    private List<MaterialType> _material;
    
    private ObjectivesTypeView _view;
    #endregion
    
    public ObjectivesType()
    {
        this._material = new List<MaterialType>();
        this._view = ObjectivesTypeView.All;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("material", ElementName="material")]
    public List<MaterialType> Material
    {
        get
        {
            return this._material;
        }
        set
        {
            this._material = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="view")]
    [System.ComponentModel.DefaultValueAttribute(ObjectivesTypeView.All)]
    public ObjectivesTypeView View
    {
        get
        {
            return this._view;
        }
        set
        {
            this._view = value;
        }
    }
}
}
#pragma warning restore
