// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="questestinteropType")]
[System.Xml.Serialization.XmlRootAttribute("questestinterop", Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", IsNullable=false, ElementName="questestinteropType")]
public partial class QuestestinteropType
{
    
    #region Private fields
    private List<ItemType> _item;
    #endregion
    
    public QuestestinteropType()
    {
        this._item = new List<ItemType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("item", ElementName="item")]
    public List<ItemType> Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
}
}
#pragma warning restore
