// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="render_choiceType")]
[System.Xml.Serialization.XmlRootAttribute("render_choice", Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", IsNullable=false, ElementName="render_choiceType")]
public partial class Render_choiceType
{
    
    #region Private fields
    private List<Response_labelType> _response_label;
    
    private Render_choiceTypeShuffle _shuffle;
    
    private string _minnumber;
    
    private string _maxnumber;
    #endregion
    
    public Render_choiceType()
    {
        this._response_label = new List<Response_labelType>();
        this._shuffle = Render_choiceTypeShuffle.No;
        this._minnumber = "1";
        this._maxnumber = "1";
    }
    
    [System.Xml.Serialization.XmlElementAttribute("response_label", ElementName="response_label")]
    public List<Response_labelType> Response_label
    {
        get
        {
            return this._response_label;
        }
        set
        {
            this._response_label = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="shuffle")]
    [System.ComponentModel.DefaultValueAttribute(Render_choiceTypeShuffle.No)]
    public Render_choiceTypeShuffle Shuffle
    {
        get
        {
            return this._shuffle;
        }
        set
        {
            this._shuffle = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="minnumber")]
    public string Minnumber
    {
        get
        {
            return this._minnumber;
        }
        set
        {
            this._minnumber = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="maxnumber")]
    public string Maxnumber
    {
        get
        {
            return this._maxnumber;
        }
        set
        {
            this._maxnumber = value;
        }
    }
}
}
#pragma warning restore
