// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="responseType")]
[System.Xml.Serialization.XmlRootAttribute("response", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="responseType")]
public partial class ResponseType
{
    
    #region Private fields
    private Qti_commentType _qti_comment;
    
    private Response_formType _response_form;
    
    private string _num_attempts;
    
    private List<Response_valueType> _response_value;
    
    private System.Xml.XmlElement _extension_response;
    
    private string _ident_ref;
    #endregion
    
    public ResponseType()
    {
        this._response_value = new List<Response_valueType>();
        this._response_form = new Response_formType();
        this._qti_comment = new Qti_commentType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("qti_comment")]
    public Qti_commentType Qti_comment
    {
        get
        {
            return this._qti_comment;
        }
        set
        {
            this._qti_comment = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("response_form")]
    public Response_formType Response_form
    {
        get
        {
            return this._response_form;
        }
        set
        {
            this._response_form = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("num_attempts")]
    public string Num_attempts
    {
        get
        {
            return this._num_attempts;
        }
        set
        {
            this._num_attempts = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("response_value", ElementName="response_value")]
    public List<Response_valueType> Response_value
    {
        get
        {
            return this._response_value;
        }
        set
        {
            this._response_value = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute(Name="extension_response", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2")]
    public System.Xml.XmlElement Extension_response
    {
        get
        {
            return this._extension_response;
        }
        set
        {
            this._extension_response = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ident_ref")]
    public string Ident_ref
    {
        get
        {
            return this._ident_ref;
        }
        set
        {
            this._ident_ref = value;
        }
    }
}
}
#pragma warning restore
