// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="response_formTypeResponse_type")]
[System.Xml.Serialization.XmlRootAttribute("response_formTypeResponse_type")]
public enum Response_formTypeResponse_type
{
    
    /// <remarks/>
    lid,
    
    /// <remarks/>
    xy,
    
    /// <remarks/>
    str,
    
    /// <remarks/>
    num,
    
    /// <remarks/>
    grp,
    
    /// <remarks/>
    extension,
}
}
#pragma warning restore
