// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="response_labelType")]
[System.Xml.Serialization.XmlRootAttribute("response_label", Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", IsNullable=false, ElementName="response_labelType")]
public partial class Response_labelType
{
    
    #region Private fields
    private List<MaterialType> _material;
    
    private Response_labelTypeRshuffle _rshuffle;
    
    private string _labelrefid;
    
    private string _ident;
    #endregion
    
    public Response_labelType()
    {
        this._material = new List<MaterialType>();
        this._rshuffle = Response_labelTypeRshuffle.Yes;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("material", ElementName="material")]
    public List<MaterialType> Material
    {
        get
        {
            return this._material;
        }
        set
        {
            this._material = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="rshuffle")]
    [System.ComponentModel.DefaultValueAttribute(Response_labelTypeRshuffle.Yes)]
    public Response_labelTypeRshuffle Rshuffle
    {
        get
        {
            return this._rshuffle;
        }
        set
        {
            this._rshuffle = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="labelrefid")]
    public string Labelrefid
    {
        get
        {
            return this._labelrefid;
        }
        set
        {
            this._labelrefid = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ident")]
    public string Ident
    {
        get
        {
            return this._ident;
        }
        set
        {
            this._ident = value;
        }
    }
}
}
#pragma warning restore
