// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="response_formType")]
[System.Xml.Serialization.XmlRootAttribute("response_form", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="response_formType")]
public partial class Response_formType
{
    
    #region Private fields
    private List<string> _correct_response;
    
    private System.Xml.XmlElement _extension_responseform;
    
    private Response_formTypeCardinality _cardinality;
    
    private Response_formTypeRender_type _render_type;
    
    private Response_formTypeTiming _timing;
    
    private Response_formTypeResponse_type _response_type;
    #endregion
    
    public Response_formType()
    {
        this._correct_response = new List<string>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("correct_response", ElementName="correct_response")]
    public List<string> Correct_response
    {
        get
        {
            return this._correct_response;
        }
        set
        {
            this._correct_response = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute(Name="extension_responseform", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2")]
    public System.Xml.XmlElement Extension_responseform
    {
        get
        {
            return this._extension_responseform;
        }
        set
        {
            this._extension_responseform = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="cardinality")]
    public Response_formTypeCardinality Cardinality
    {
        get
        {
            return this._cardinality;
        }
        set
        {
            this._cardinality = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="render_type")]
    public Response_formTypeRender_type Render_type
    {
        get
        {
            return this._render_type;
        }
        set
        {
            this._render_type = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="timing")]
    public Response_formTypeTiming Timing
    {
        get
        {
            return this._timing;
        }
        set
        {
            this._timing = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="response_type")]
    public Response_formTypeResponse_type Response_type
    {
        get
        {
            return this._response_type;
        }
        set
        {
            this._response_type = value;
        }
    }
}
}
#pragma warning restore
