// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", TypeName="setvarType")]
[System.Xml.Serialization.XmlRootAttribute("setvar", Namespace="http://www.imsglobal.org/xsd/ims_qtilitev1p2", IsNullable=false, ElementName="setvarType")]
public partial class SetvarType
{
    
    #region Private fields
    private string _varname;
    
    private SetvarTypeAction _action;
    
    private string _value;
    #endregion
    
    public SetvarType()
    {
        this._varname = "SCORE";
        this._action = SetvarTypeAction.Set;
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="varname")]
    [System.ComponentModel.DefaultValueAttribute("SCORE")]
    public string Varname
    {
        get
        {
            return this._varname;
        }
        set
        {
            this._varname = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="action")]
    [System.ComponentModel.DefaultValueAttribute(SetvarTypeAction.Set)]
    public SetvarTypeAction Action
    {
        get
        {
            return this._action;
        }
        set
        {
            this._action = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
