// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="statusType")]
[System.Xml.Serialization.XmlRootAttribute("status", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="statusType")]
public partial class StatusType
{
    
    #region Private fields
    private Type_labelType _type_label;
    
    private string _datetime;
    
    private string _status_value;
    #endregion
    
    public StatusType()
    {
        this._type_label = new Type_labelType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("type_label")]
    public Type_labelType Type_label
    {
        get
        {
            return this._type_label;
        }
        set
        {
            this._type_label = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("datetime")]
    public string Datetime
    {
        get
        {
            return this._datetime;
        }
        set
        {
            this._datetime = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("status_value")]
    public string Status_value
    {
        get
        {
            return this._status_value;
        }
        set
        {
            this._status_value = value;
        }
    }
}
}
#pragma warning restore
