// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", TypeName="summary_resultType")]
[System.Xml.Serialization.XmlRootAttribute("summary_result", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2", IsNullable=false, ElementName="summary_resultType")]
public partial class Summary_resultType
{
    
    #region Private fields
    private Qti_commentType _qti_comment;
    
    private Type_labelType _type_label;
    
    private List<Generic_identifierType> _generic_identifier;
    
    private List<DateType> _date;
    
    private StatusType _status;
    
    private string _duration;
    
    private ScoreType _score;
    
    private GradeType _grade;
    
    private OutcomesType _outcomes;
    
    private System.Xml.XmlElement _extension_summary_result;
    
    private string _asi_title;
    #endregion
    
    public Summary_resultType()
    {
        this._outcomes = new OutcomesType();
        this._grade = new GradeType();
        this._score = new ScoreType();
        this._status = new StatusType();
        this._date = new List<DateType>();
        this._generic_identifier = new List<Generic_identifierType>();
        this._type_label = new Type_labelType();
        this._qti_comment = new Qti_commentType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("qti_comment")]
    public Qti_commentType Qti_comment
    {
        get
        {
            return this._qti_comment;
        }
        set
        {
            this._qti_comment = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("type_label")]
    public Type_labelType Type_label
    {
        get
        {
            return this._type_label;
        }
        set
        {
            this._type_label = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("generic_identifier", ElementName="generic_identifier")]
    public List<Generic_identifierType> Generic_identifier
    {
        get
        {
            return this._generic_identifier;
        }
        set
        {
            this._generic_identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("date", ElementName="date")]
    public List<DateType> Date
    {
        get
        {
            return this._date;
        }
        set
        {
            this._date = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("status")]
    public StatusType Status
    {
        get
        {
            return this._status;
        }
        set
        {
            this._status = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("duration")]
    public string Duration
    {
        get
        {
            return this._duration;
        }
        set
        {
            this._duration = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("score")]
    public ScoreType Score
    {
        get
        {
            return this._score;
        }
        set
        {
            this._score = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("grade")]
    public GradeType Grade
    {
        get
        {
            return this._grade;
        }
        set
        {
            this._grade = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("outcomes")]
    public OutcomesType Outcomes
    {
        get
        {
            return this._outcomes;
        }
        set
        {
            this._outcomes = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute(Name="extension_summary_result", Namespace="http://www.imsglobal.org/xsd/ims_qtiresv1p2")]
    public System.Xml.XmlElement Extension_summary_result
    {
        get
        {
            return this._extension_summary_result;
        }
        set
        {
            this._extension_summary_result = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="asi_title")]
    public string Asi_title
    {
        get
        {
            return this._asi_title;
        }
        set
        {
            this._asi_title = value;
        }
    }
}
}
#pragma warning restore
