// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="decvarType")]
[System.Xml.Serialization.XmlRootAttribute("decvarType")]
public partial class DecvarType
{
    
    #region Private fields
    private string _varname;
    
    private DecvarTypeVartype _vartype;
    
    private string _minvalue;
    
    private string _maxvalue;
    
    private string _value;
    #endregion
    
    public DecvarType()
    {
        this._varname = "SCORE";
        this._vartype = DecvarTypeVartype.Integer;
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="varname")]
    public string Varname
    {
        get
        {
            return this._varname;
        }
        set
        {
            this._varname = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="vartype")]
    [System.ComponentModel.DefaultValueAttribute(DecvarTypeVartype.Integer)]
    public DecvarTypeVartype Vartype
    {
        get
        {
            return this._vartype;
        }
        set
        {
            this._vartype = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="minvalue")]
    public string Minvalue
    {
        get
        {
            return this._minvalue;
        }
        set
        {
            this._minvalue = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="maxvalue")]
    public string Maxvalue
    {
        get
        {
            return this._maxvalue;
        }
        set
        {
            this._maxvalue = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
