// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="displayfeedbackType")]
[System.Xml.Serialization.XmlRootAttribute("displayfeedbackType")]
public partial class DisplayfeedbackType
{
    
    #region Private fields
    private DisplayfeedbackTypeFeedbacktype _feedbacktype;
    
    private string _linkrefid;
    
    private string _value;
    #endregion
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="feedbacktype")]
    public DisplayfeedbackTypeFeedbacktype Feedbacktype
    {
        get
        {
            return this._feedbacktype;
        }
        set
        {
            this._feedbacktype = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="linkrefid")]
    public string Linkrefid
    {
        get
        {
            return this._linkrefid;
        }
        set
        {
            this._linkrefid = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
