// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="flow_matType")]
[System.Xml.Serialization.XmlRootAttribute("flow_matType")]
public partial class Flow_matType
{
    
    #region Private fields
    private List<object> _items;
    
    private string _class;
    #endregion
    
    public Flow_matType()
    {
        this._items = new List<object>();
        this._class = "Block";
    }
    
    [System.Xml.Serialization.XmlElementAttribute("flow_mat", typeof(Flow_matType))]
    [System.Xml.Serialization.XmlElementAttribute("material", typeof(MaterialType))]
    [System.Xml.Serialization.XmlElementAttribute("material_ref", typeof(Material_refType))]
    public List<object> Items
    {
        get
        {
            return this._items;
        }
        set
        {
            this._items = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
    [System.ComponentModel.DefaultValueAttribute("Block")]
    public string Class
    {
        get
        {
            return this._class;
        }
        set
        {
            this._class = value;
        }
    }
}
}
#pragma warning restore
