// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="itemfeedbackType")]
[System.Xml.Serialization.XmlRootAttribute("itemfeedbackType")]
public partial class ItemfeedbackType
{
    
    #region Private fields
    private List<object> _items;
    
    private string _ident;
    
    private string _title;
    #endregion
    
    public ItemfeedbackType()
    {
        this._items = new List<object>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("flow_mat", typeof(Flow_matType))]
    [System.Xml.Serialization.XmlElementAttribute("hint", typeof(HintType))]
    [System.Xml.Serialization.XmlElementAttribute("material", typeof(MaterialType))]
    [System.Xml.Serialization.XmlElementAttribute("solution", typeof(SolutionType))]
    public List<object> Items
    {
        get
        {
            return this._items;
        }
        set
        {
            this._items = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ident")]
    public string Ident
    {
        get
        {
            return this._ident;
        }
        set
        {
            this._ident = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="title")]
    public string Title
    {
        get
        {
            return this._title;
        }
        set
        {
            this._title = value;
        }
    }
}
}
#pragma warning restore
