// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName = "itemmetadataType")]
    [System.Xml.Serialization.XmlRootAttribute("itemmetadataType")]
    public partial class ItemmetadataType
    {

        #region Private fields
        private QtimetadataType _qtimetadata;
        #endregion

        [System.Xml.Serialization.XmlElementAttribute("qtimetadata", ElementName = "qtimetadata")]
        public QtimetadataType Qtimetadata
        {
            get
            {
                return this._qtimetadata;
            }
            set
            {
                this._qtimetadata = value;
            }
        }
    }
}
#pragma warning restore
