// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="material_refType")]
[System.Xml.Serialization.XmlRootAttribute("material_refType")]
public partial class Material_refType : EmptyPrimitiveTypeType
{
    
    #region Private fields
    private string _linkrefid;
    #endregion
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="linkrefid")]
    public string Linkrefid
    {
        get
        {
            return this._linkrefid;
        }
        set
        {
            this._linkrefid = value;
        }
    }
}
}
#pragma warning restore
