// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName = "qtimetadataType")]
    [System.Xml.Serialization.XmlRootAttribute("qtimetadataType")]
    public partial class QtimetadataType
    {

        #region Private fields
        private List<QtimetadatafieldType> _qtimetadatafield;
        #endregion

        public QtimetadataType()
        {
            this._qtimetadatafield = new List<QtimetadatafieldType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("qtimetadatafield", ElementName ="qtimetadatafield")]
        public List<QtimetadatafieldType> Qtimetadatafield
        {
            get
            {
                return this._qtimetadatafield;
            }
            set
            {
                this._qtimetadatafield = value;
            }
        }
    }
}
#pragma warning restore
