// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="respconditionType")]
[System.Xml.Serialization.XmlRootAttribute("respconditionType")]
public partial class RespconditionType
{
    
    #region Private fields
    private ConditionvarType _conditionvar;
    
    private List<SetvarType> _setvar;
    
    private List<DisplayfeedbackType> _displayfeedback;
    
    private string _title;
    
    private RespconditionTypeContinue _continue;
    #endregion
    
    public RespconditionType()
    {
        this._displayfeedback = new List<DisplayfeedbackType>();
        this._setvar = new List<SetvarType>();
        this._conditionvar = new ConditionvarType();
        this._continue = RespconditionTypeContinue.No;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("conditionvar")]
    public ConditionvarType Conditionvar
    {
        get
        {
            return this._conditionvar;
        }
        set
        {
            this._conditionvar = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("setvar", ElementName="setvar")]
    public List<SetvarType> Setvar
    {
        get
        {
            return this._setvar;
        }
        set
        {
            this._setvar = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("displayfeedback", ElementName="displayfeedback")]
    public List<DisplayfeedbackType> Displayfeedback
    {
        get
        {
            return this._displayfeedback;
        }
        set
        {
            this._displayfeedback = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="title")]
    public string Title
    {
        get
        {
            return this._title;
        }
        set
        {
            this._title = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="continue")]
    [System.ComponentModel.DefaultValueAttribute(RespconditionTypeContinue.No)]
    public RespconditionTypeContinue Continue
    {
        get
        {
            return this._continue;
        }
        set
        {
            this._continue = value;
        }
    }
}
}
#pragma warning restore
