// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="response_strType")]
[System.Xml.Serialization.XmlRootAttribute("response_strType")]
public partial class Response_strType
{
    
    #region Private fields
    private object _item;
    
    private object _item1;
    
    private object _item2;
    
    private Response_strTypeRcardinality _rcardinality;
    
    private Response_strTypeRtiming _rtiming;
    
    private string _ident;
    #endregion
    
    public Response_strType()
    {
        this._rcardinality = Response_strTypeRcardinality.Single;
        this._rtiming = Response_strTypeRtiming.No;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("material", typeof(MaterialType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("material_ref", typeof(Material_refType), Order=0)]
    public object Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("render_choice", typeof(Render_choiceType), Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("render_fib", typeof(Render_fibType), Order=1)]
    public object Item1
    {
        get
        {
            return this._item1;
        }
        set
        {
            this._item1 = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("material", typeof(MaterialType), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("material_ref", typeof(Material_refType), Order=2)]
    public object Item2
    {
        get
        {
            return this._item2;
        }
        set
        {
            this._item2 = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="rcardinality")]
    [System.ComponentModel.DefaultValueAttribute(Response_strTypeRcardinality.Single)]
    public Response_strTypeRcardinality Rcardinality
    {
        get
        {
            return this._rcardinality;
        }
        set
        {
            this._rcardinality = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="rtiming")]
    [System.ComponentModel.DefaultValueAttribute(Response_strTypeRtiming.No)]
    public Response_strTypeRtiming Rtiming
    {
        get
        {
            return this._rtiming;
        }
        set
        {
            this._rtiming = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ident")]
    public string Ident
    {
        get
        {
            return this._ident;
        }
        set
        {
            this._ident = value;
        }
    }
}
}
#pragma warning restore
