// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.QTIv1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/ims_qtiasiv1p2", TypeName="response_lidTypeRtiming")]
[System.Xml.Serialization.XmlRootAttribute("response_lidTypeRtiming")]
public enum Response_lidTypeRtiming
{
    
    /// <remarks/>
    Yes,
    
    /// <remarks/>
    No,
}
}
#pragma warning restore
