// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="AreaMapEntry.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("areaMapEntry", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class AreaMapEntryType : EmptyPrimitiveTypeType
{
    
    #region Private fields
    private AreaMapEntryTypeShape _shape;
    
    private string _coords;
    
    private double _mappedValue;
    #endregion
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="shape")]
    public AreaMapEntryTypeShape Shape
    {
        get
        {
            return this._shape;
        }
        set
        {
            this._shape = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="coords")]
    public string Coords
    {
        get
        {
            return this._coords;
        }
        set
        {
            this._coords = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="mappedValue")]
    public double MappedValue
    {
        get
        {
            return this._mappedValue;
        }
        set
        {
            this._mappedValue = value;
        }
    }
}
}
#pragma warning restore
