// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="AssessmentItemRef.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("assessmentItemRef", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class AssessmentItemRefType
{
    
    #region Private fields
    private List<LogicSingleType> _preCondition;
    
    private List<BranchRuleType> _branchRule;
    
    private ItemSessionControlType _itemSessionControl;
    
    private TimeLimitsType _timeLimits;
    
    private List<VariableMappingType> _variableMapping;
    
    private List<WeightType> _weight;
    
    private List<TemplateDefaultType> _templateDefault;
    
    private string _identifier;
    
    private bool _required;
    
    private bool _fixed;
    
    private string _href;
    
    private List<string> _category;
    #endregion
    
    public AssessmentItemRefType()
    {
        this._category = new List<string>();
        this._templateDefault = new List<TemplateDefaultType>();
        this._weight = new List<WeightType>();
        this._variableMapping = new List<VariableMappingType>();
        this._timeLimits = new TimeLimitsType();
        this._itemSessionControl = new ItemSessionControlType();
        this._branchRule = new List<BranchRuleType>();
        this._preCondition = new List<LogicSingleType>();
        this._required = false;
        this._fixed = false;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("preCondition", ElementName="preCondition")]
    public List<LogicSingleType> PreCondition
    {
        get
        {
            return this._preCondition;
        }
        set
        {
            this._preCondition = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("branchRule", ElementName="branchRule")]
    public List<BranchRuleType> BranchRule
    {
        get
        {
            return this._branchRule;
        }
        set
        {
            this._branchRule = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("itemSessionControl")]
    public ItemSessionControlType ItemSessionControl
    {
        get
        {
            return this._itemSessionControl;
        }
        set
        {
            this._itemSessionControl = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("timeLimits")]
    public TimeLimitsType TimeLimits
    {
        get
        {
            return this._timeLimits;
        }
        set
        {
            this._timeLimits = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("variableMapping", ElementName="variableMapping")]
    public List<VariableMappingType> VariableMapping
    {
        get
        {
            return this._variableMapping;
        }
        set
        {
            this._variableMapping = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("weight", ElementName="weight")]
    public List<WeightType> Weight
    {
        get
        {
            return this._weight;
        }
        set
        {
            this._weight = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("templateDefault", ElementName="templateDefault")]
    public List<TemplateDefaultType> TemplateDefault
    {
        get
        {
            return this._templateDefault;
        }
        set
        {
            this._templateDefault = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="required")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Required
    {
        get
        {
            return this._required;
        }
        set
        {
            this._required = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="fixed")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Fixed
    {
        get
        {
            return this._fixed;
        }
        set
        {
            this._fixed = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="href")]
    public string Href
    {
        get
        {
            return this._href;
        }
        set
        {
            this._href = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="category")]
    public List<string> Category
    {
        get
        {
            return this._category;
        }
        set
        {
            this._category = value;
        }
    }
}
}
#pragma warning restore
