// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CharacterStringLink.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("CharacterStringLinkType")]
public partial class CharacterStringLinkType
{
    
    #region Private fields
    private string _startCharacter;
    
    private string _stopCharacter;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="startCharacter")]
    public string StartCharacter
    {
        get
        {
            return this._startCharacter;
        }
        set
        {
            this._startCharacter = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="stopCharacter")]
    public string StopCharacter
    {
        get
        {
            return this._stopCharacter;
        }
        set
        {
            this._stopCharacter = value;
        }
    }
}
}
#pragma warning restore
