// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ContentLinkInfo.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("ContentLinkInfoType")]
public partial class ContentLinkInfoType
{
    
    #region Private fields
    private object _item;
    
    private string _apipLinkIdentifierRef;
    
    private string _qtiLinkIdentifierRef;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute("objectLink", typeof(EmptyPrimitiveTypeType1))]
    [System.Xml.Serialization.XmlElementAttribute("textLink", typeof(TextLinkType))]
    public object Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF", AttributeName="apipLinkIdentifierRef")]
    public string ApipLinkIdentifierRef
    {
        get
        {
            return this._apipLinkIdentifierRef;
        }
        set
        {
            this._apipLinkIdentifierRef = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="qtiLinkIdentifierRef")]
    public string QtiLinkIdentifierRef
    {
        get
        {
            return this._qtiLinkIdentifierRef;
        }
        set
        {
            this._qtiLinkIdentifierRef = value;
        }
    }
}
}
#pragma warning restore
