// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Context.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_result_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("ContextType")]
public partial class ContextType
{
    
    #region Private fields
    private List<SessionIdentifierType> _sessionIdentifier;
    
    private string _sourcedId;
    #endregion
    
    public ContextType()
    {
        this._sessionIdentifier = new List<SessionIdentifierType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("sessionIdentifier", ElementName="sessionIdentifier")]
    public List<SessionIdentifierType> SessionIdentifier
    {
        get
        {
            return this._sessionIdentifier;
        }
        set
        {
            this._sessionIdentifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="sourcedId")]
    public string SourcedId
    {
        get
        {
            return this._sourcedId;
        }
        set
        {
            this._sourcedId = value;
        }
    }
}
}
#pragma warning restore
