// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ElementOrder.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("ElementOrderType")]
public partial class ElementOrderType
{
    
    #region Private fields
    private string _order;
    
    private string _identifierRef;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="order")]
    public string Order
    {
        get
        {
            return this._order;
        }
        set
        {
            this._order = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF", AttributeName="identifierRef")]
    public string IdentifierRef
    {
        get
        {
            return this._identifierRef;
        }
        set
        {
            this._identifierRef = value;
        }
    }
}
}
#pragma warning restore
