// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="GraphicGapMatchInteraction.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("graphicGapMatchInteraction", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class GraphicGapMatchInteractionType
{
    
    #region Private fields
    private PromptType _prompt;
    
    private ObjectType _object;
    
    private List<GapImgType> _gapImg;
    
    private List<AssociableHotspotType> _associableHotspot;
    
    private string _base;
    
    private string _id;
    
    private List<string> _class;
    
    private string _lang;
    
    private string _label;
    
    private string _responseIdentifier;
    #endregion
    
    public GraphicGapMatchInteractionType()
    {
        this._class = new List<string>();
        this._associableHotspot = new List<AssociableHotspotType>();
        this._gapImg = new List<GapImgType>();
        this._object = new ObjectType();
        this._prompt = new PromptType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("prompt")]
    public PromptType Prompt
    {
        get
        {
            return this._prompt;
        }
        set
        {
            this._prompt = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("object")]
    public ObjectType Object
    {
        get
        {
            return this._object;
        }
        set
        {
            this._object = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("gapImg", ElementName="gapImg")]
    public List<GapImgType> GapImg
    {
        get
        {
            return this._gapImg;
        }
        set
        {
            this._gapImg = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("associableHotspot", ElementName="associableHotspot")]
    public List<AssociableHotspotType> AssociableHotspot
    {
        get
        {
            return this._associableHotspot;
        }
        set
        {
            this._associableHotspot = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="base")]
    public string Base
    {
        get
        {
            return this._base;
        }
        set
        {
            this._base = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="id")]
    public string Id
    {
        get
        {
            return this._id;
        }
        set
        {
            this._id = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
    public List<string> Class
    {
        get
        {
            return this._class;
        }
        set
        {
            this._class = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
    public string Lang
    {
        get
        {
            return this._lang;
        }
        set
        {
            this._lang = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="label")]
    public string Label
    {
        get
        {
            return this._label;
        }
        set
        {
            this._label = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="responseIdentifier")]
    public string ResponseIdentifier
    {
        get
        {
            return this._responseIdentifier;
        }
        set
        {
            this._responseIdentifier = value;
        }
    }
}
}
#pragma warning restore
