// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="IncrementUS.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("IncrementUSType")]
public partial class IncrementUSType
{
    
    #region Private fields
    private RadialUSValueType _minorIncrement;
    
    private RadialUSValueType _majorIncrement;
    #endregion
    
    public IncrementUSType()
    {
        this._majorIncrement = new RadialUSValueType();
        this._minorIncrement = new RadialUSValueType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("minorIncrement")]
    public RadialUSValueType MinorIncrement
    {
        get
        {
            return this._minorIncrement;
        }
        set
        {
            this._minorIncrement = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("majorIncrement")]
    public RadialUSValueType MajorIncrement
    {
        get
        {
            return this._majorIncrement;
        }
        set
        {
            this._majorIncrement = value;
        }
    }
}
}
#pragma warning restore
