// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="InterpolationTableEntry.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("interpolationTableEntry", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class InterpolationTableEntryType : EmptyPrimitiveTypeType
{
    
    #region Private fields
    private double _sourceValue;
    
    private bool _includeBoundary;
    
    private string _targetValue;
    #endregion
    
    public InterpolationTableEntryType()
    {
        this._includeBoundary = true;
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="sourceValue")]
    public double SourceValue
    {
        get
        {
            return this._sourceValue;
        }
        set
        {
            this._sourceValue = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="includeBoundary")]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool IncludeBoundary
    {
        get
        {
            return this._includeBoundary;
        }
        set
        {
            this._includeBoundary = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="targetValue")]
    public string TargetValue
    {
        get
        {
            return this._targetValue;
        }
        set
        {
            this._targetValue = value;
        }
    }
}
}
#pragma warning restore
