// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="InterpolationTable.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("interpolationTable", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class InterpolationTableType
{
    
    #region Private fields
    private List<InterpolationTableEntryType> _interpolationTableEntry;
    
    private string _defaultValue;
    #endregion
    
    public InterpolationTableType()
    {
        this._interpolationTableEntry = new List<InterpolationTableEntryType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("interpolationTableEntry", ElementName="interpolationTableEntry")]
    public List<InterpolationTableEntryType> InterpolationTableEntry
    {
        get
        {
            return this._interpolationTableEntry;
        }
        set
        {
            this._interpolationTableEntry = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="defaultValue")]
    public string DefaultValue
    {
        get
        {
            return this._defaultValue;
        }
        set
        {
            this._defaultValue = value;
        }
    }
}
}
#pragma warning restore
