// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IncludeInSchema=false)]
[System.Xml.Serialization.XmlRootAttribute("ItemsChoiceType12")]
public enum ItemsChoiceType12
{
    
    /// <remarks/>
    baseValue,
    
    /// <remarks/>
    containerSize,
    
    /// <remarks/>
    correct,
    
    /// <remarks/>
    customOperator,
    
    /// <remarks/>
    @default,
    
    /// <remarks/>
    delete,
    
    /// <remarks/>
    divide,
    
    /// <remarks/>
    fieldValue,
    
    /// <remarks/>
    gcd,
    
    /// <remarks/>
    index,
    
    /// <remarks/>
    integerDivide,
    
    /// <remarks/>
    integerModulus,
    
    /// <remarks/>
    integerToFloat,
    
    /// <remarks/>
    lcm,
    
    /// <remarks/>
    mapResponse,
    
    /// <remarks/>
    mapResponsePoint,
    
    /// <remarks/>
    mathConstant,
    
    /// <remarks/>
    mathOperator,
    
    /// <remarks/>
    max,
    
    /// <remarks/>
    min,
    
    /// <remarks/>
    multiple,
    
    /// <remarks/>
    @null,
    
    /// <remarks/>
    numberCorrect,
    
    /// <remarks/>
    numberIncorrect,
    
    /// <remarks/>
    numberPresented,
    
    /// <remarks/>
    numberResponded,
    
    /// <remarks/>
    numberSelected,
    
    /// <remarks/>
    ordered,
    
    /// <remarks/>
    outcomeMaximum,
    
    /// <remarks/>
    outcomeMinimum,
    
    /// <remarks/>
    power,
    
    /// <remarks/>
    product,
    
    /// <remarks/>
    random,
    
    /// <remarks/>
    randomFloat,
    
    /// <remarks/>
    randomInteger,
    
    /// <remarks/>
    repeat,
    
    /// <remarks/>
    round,
    
    /// <remarks/>
    roundTo,
    
    /// <remarks/>
    statsOperator,
    
    /// <remarks/>
    subtract,
    
    /// <remarks/>
    sum,
    
    /// <remarks/>
    testVariables,
    
    /// <remarks/>
    truncate,
    
    /// <remarks/>
    variable,
}
}
#pragma warning restore
