// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IncludeInSchema=false)]
[System.Xml.Serialization.XmlRootAttribute("ItemsChoiceType35")]
public enum ItemsChoiceType35
{
    
    /// <remarks/>
    a,
    
    /// <remarks/>
    abbr,
    
    /// <remarks/>
    acronym,
    
    /// <remarks/>
    b,
    
    /// <remarks/>
    big,
    
    /// <remarks/>
    br,
    
    /// <remarks/>
    cite,
    
    /// <remarks/>
    code,
    
    /// <remarks/>
    dfn,
    
    /// <remarks/>
    em,
    
    /// <remarks/>
    i,
    
    /// <remarks/>
    img,
    
    /// <remarks/>
    kbd,
    
    /// <remarks/>
    @object,
    
    /// <remarks/>
    printedVariable,
    
    /// <remarks/>
    q,
    
    /// <remarks/>
    samp,
    
    /// <remarks/>
    small,
    
    /// <remarks/>
    span,
    
    /// <remarks/>
    strong,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
    
    /// <remarks/>
    templateInline,
    
    /// <remarks/>
    tt,
    
    /// <remarks/>
    var,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/1998/Math/MathML:math")]
    math,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2001/XInclude:include")]
    include,
}
}
#pragma warning restore
