// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0", IncludeInSchema=false)]
[System.Xml.Serialization.XmlRootAttribute("ItemChoiceType10")]
public enum ItemChoiceType10
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    audioFileInfo,
    
    /// <remarks/>
    executableFileInfo,
    
    /// <remarks/>
    graphicFileInfo,
    
    /// <remarks/>
    markupFileEmbedded,
    
    /// <remarks/>
    markupFileInfo,
    
    /// <remarks/>
    textFileInfo,
    
    /// <remarks/>
    textString,
    
    /// <remarks/>
    videoFileInfo,
}
}
#pragma warning restore
