// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IncludeInSchema=false)]
[System.Xml.Serialization.XmlRootAttribute("ItemsChoiceType37")]
public enum ItemsChoiceType37
{
    
    /// <remarks/>
    address,
    
    /// <remarks/>
    associateInteraction,
    
    /// <remarks/>
    blockquote,
    
    /// <remarks/>
    choiceInteraction,
    
    /// <remarks/>
    customInteraction,
    
    /// <remarks/>
    div,
    
    /// <remarks/>
    dl,
    
    /// <remarks/>
    drawingInteraction,
    
    /// <remarks/>
    extendedTextInteraction,
    
    /// <remarks/>
    feedbackBlock,
    
    /// <remarks/>
    gapMatchInteraction,
    
    /// <remarks/>
    graphicAssociateInteraction,
    
    /// <remarks/>
    graphicGapMatchInteraction,
    
    /// <remarks/>
    graphicOrderInteraction,
    
    /// <remarks/>
    h1,
    
    /// <remarks/>
    h2,
    
    /// <remarks/>
    h3,
    
    /// <remarks/>
    h4,
    
    /// <remarks/>
    h5,
    
    /// <remarks/>
    h6,
    
    /// <remarks/>
    hotspotInteraction,
    
    /// <remarks/>
    hottextInteraction,
    
    /// <remarks/>
    hr,
    
    /// <remarks/>
    infoControl,
    
    /// <remarks/>
    matchInteraction,
    
    /// <remarks/>
    mediaInteraction,
    
    /// <remarks/>
    ol,
    
    /// <remarks/>
    orderInteraction,
    
    /// <remarks/>
    p,
    
    /// <remarks/>
    positionObjectStage,
    
    /// <remarks/>
    pre,
    
    /// <remarks/>
    rubricBlock,
    
    /// <remarks/>
    selectPointInteraction,
    
    /// <remarks/>
    sliderInteraction,
    
    /// <remarks/>
    table,
    
    /// <remarks/>
    templateBlock,
    
    /// <remarks/>
    ul,
    
    /// <remarks/>
    uploadInteraction,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/1998/Math/MathML:math")]
    math,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2001/XInclude:include")]
    include,
}
}
#pragma warning restore
