// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="KeyWordTranslation.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("KeyWordTranslationType")]
public partial class KeyWordTranslationType
{
    
    #region Private fields
    private List<DefinitionIdType> _definitionId;
    #endregion
    
    public KeyWordTranslationType()
    {
        this._definitionId = new List<DefinitionIdType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("definitionId", ElementName="definitionId")]
    public List<DefinitionIdType> DefinitionId
    {
        get
        {
            return this._definitionId;
        }
        set
        {
            this._definitionId = value;
        }
    }
}
}
#pragma warning restore
