// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="MatchInteraction.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("matchInteraction", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class MatchInteractionType
{
    
    #region Private fields
    private PromptType _prompt;
    
    private List<SimpleAssociableChoiceType> _simpleMatchSet;
    
    private string _base;
    
    private string _id;
    
    private List<string> _class;
    
    private string _lang;
    
    private string _label;
    
    private string _responseIdentifier;
    
    private bool _shuffle;
    
    private int _maxAssociations;
    
    private int _minAssociations;
    #endregion
    
    public MatchInteractionType()
    {
        this._class = new List<string>();
        this._simpleMatchSet = new List<SimpleAssociableChoiceType>();
        this._prompt = new PromptType();
        this._shuffle = false;
        this._maxAssociations = 1;
        this._minAssociations = 0;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("prompt")]
    public PromptType Prompt
    {
        get
        {
            return this._prompt;
        }
        set
        {
            this._prompt = value;
        }
    }
    
    [System.Xml.Serialization.XmlArrayItemAttribute("simpleAssociableChoice", typeof(SimpleAssociableChoiceType), IsNullable=false, ElementName="simpleMatchSet")]
    public List<SimpleAssociableChoiceType> SimpleMatchSet
    {
        get
        {
            return this._simpleMatchSet;
        }
        set
        {
            this._simpleMatchSet = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="base")]
    public string Base
    {
        get
        {
            return this._base;
        }
        set
        {
            this._base = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="id")]
    public string Id
    {
        get
        {
            return this._id;
        }
        set
        {
            this._id = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
    public List<string> Class
    {
        get
        {
            return this._class;
        }
        set
        {
            this._class = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
    public string Lang
    {
        get
        {
            return this._lang;
        }
        set
        {
            this._lang = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="label")]
    public string Label
    {
        get
        {
            return this._label;
        }
        set
        {
            this._label = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="responseIdentifier")]
    public string ResponseIdentifier
    {
        get
        {
            return this._responseIdentifier;
        }
        set
        {
            this._responseIdentifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="shuffle")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Shuffle
    {
        get
        {
            return this._shuffle;
        }
        set
        {
            this._shuffle = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="maxAssociations")]
    [System.ComponentModel.DefaultValueAttribute(1)]
    public int MaxAssociations
    {
        get
        {
            return this._maxAssociations;
        }
        set
        {
            this._maxAssociations = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="minAssociations")]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int MinAssociations
    {
        get
        {
            return this._minAssociations;
        }
        set
        {
            this._minAssociations = value;
        }
    }
}
}
#pragma warning restore
