// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("MathOperatorTypeName")]
public enum MathOperatorTypeName
{
    
    /// <remarks/>
    sin,
    
    /// <remarks/>
    cos,
    
    /// <remarks/>
    tan,
    
    /// <remarks/>
    sec,
    
    /// <remarks/>
    csc,
    
    /// <remarks/>
    cot,
    
    /// <remarks/>
    asin,
    
    /// <remarks/>
    acos,
    
    /// <remarks/>
    atan,
    
    /// <remarks/>
    atan2,
    
    /// <remarks/>
    asec,
    
    /// <remarks/>
    acsc,
    
    /// <remarks/>
    acot,
    
    /// <remarks/>
    sinh,
    
    /// <remarks/>
    cosh,
    
    /// <remarks/>
    tanh,
    
    /// <remarks/>
    sech,
    
    /// <remarks/>
    csch,
    
    /// <remarks/>
    coth,
    
    /// <remarks/>
    log,
    
    /// <remarks/>
    ln,
    
    /// <remarks/>
    exp,
    
    /// <remarks/>
    abs,
    
    /// <remarks/>
    signum,
    
    /// <remarks/>
    floor,
    
    /// <remarks/>
    ceil,
    
    /// <remarks/>
    toDegrees,
    
    /// <remarks/>
    toRadians,
}
}
#pragma warning restore
