// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="OutcomeDeclaration.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("outcomeDeclaration", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class OutcomeDeclarationType
{
    
    #region Private fields
    private DefaultValueType _defaultValue;
    
    private object _item;
    
    private string _identifier;
    
    private OutcomeDeclarationTypeCardinality _cardinality;
    
    private OutcomeDeclarationTypeBaseType _baseType;
    
    private List<ViewType> _view;
    
    private string _interpretation;
    
    private string _longInterpretation;
    
    private double _normalMaximum;
    
    private double _normalMinimum;
    
    private double _masteryValue;
    #endregion
    
    public OutcomeDeclarationType()
    {
        this._view = new List<ViewType>();
        this._defaultValue = new DefaultValueType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("defaultValue")]
    public DefaultValueType DefaultValue
    {
        get
        {
            return this._defaultValue;
        }
        set
        {
            this._defaultValue = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("interpolationTable", typeof(InterpolationTableType))]
    [System.Xml.Serialization.XmlElementAttribute("matchTable", typeof(MatchTableType))]
    public object Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="cardinality")]
    public OutcomeDeclarationTypeCardinality Cardinality
    {
        get
        {
            return this._cardinality;
        }
        set
        {
            this._cardinality = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="baseType")]
    public OutcomeDeclarationTypeBaseType BaseType
    {
        get
        {
            return this._baseType;
        }
        set
        {
            this._baseType = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="view")]
    public List<ViewType> View
    {
        get
        {
            return this._view;
        }
        set
        {
            this._view = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="interpretation")]
    public string Interpretation
    {
        get
        {
            return this._interpretation;
        }
        set
        {
            this._interpretation = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="longInterpretation")]
    public string LongInterpretation
    {
        get
        {
            return this._longInterpretation;
        }
        set
        {
            this._longInterpretation = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="normalMaximum")]
    public double NormalMaximum
    {
        get
        {
            return this._normalMaximum;
        }
        set
        {
            this._normalMaximum = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="normalMinimum")]
    public double NormalMinimum
    {
        get
        {
            return this._normalMinimum;
        }
        set
        {
            this._normalMinimum = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="masteryValue")]
    public double MasteryValue
    {
        get
        {
            return this._masteryValue;
        }
        set
        {
            this._masteryValue = value;
        }
    }
}
}
#pragma warning restore
