// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="PositionObjectStage.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("positionObjectStage", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class PositionObjectStageType
{
    
    #region Private fields
    private ObjectType _object;
    
    private List<PositionObjectInteractionType> _positionObjectInteraction;
    #endregion
    
    public PositionObjectStageType()
    {
        this._positionObjectInteraction = new List<PositionObjectInteractionType>();
        this._object = new ObjectType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("object")]
    public ObjectType Object
    {
        get
        {
            return this._object;
        }
        set
        {
            this._object = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("positionObjectInteraction", ElementName="positionObjectInteraction")]
    public List<PositionObjectInteractionType> PositionObjectInteraction
    {
        get
        {
            return this._positionObjectInteraction;
        }
        set
        {
            this._positionObjectInteraction = value;
        }
    }
}
}
#pragma warning restore
