// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="PrintedVariable.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("printedVariable", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class PrintedVariableType : EmptyPrimitiveTypeType
{
    
    #region Private fields
    private string _id;
    
    private List<string> _class;
    
    private string _lang;
    
    private string _label;
    
    private string _base;
    
    private string _identifier;
    
    private string _format;
    
    private string _base1;
    
    private string _index;
    
    private bool _powerForm;
    
    private string _field;
    
    private string _delimiter;
    
    private string _mappingIndicator;
    #endregion
    
    public PrintedVariableType()
    {
        this._class = new List<string>();
        this._base1 = "10";
        this._powerForm = false;
        this._delimiter = ";";
        this._mappingIndicator = "=";
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="id")]
    public string Id
    {
        get
        {
            return this._id;
        }
        set
        {
            this._id = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
    public List<string> Class
    {
        get
        {
            return this._class;
        }
        set
        {
            this._class = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
    public string Lang
    {
        get
        {
            return this._lang;
        }
        set
        {
            this._lang = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="label")]
    public string Label
    {
        get
        {
            return this._label;
        }
        set
        {
            this._label = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="base")]
    public string Base
    {
        get
        {
            return this._base;
        }
        set
        {
            this._base = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="format")]
    public string Format
    {
        get
        {
            return this._format;
        }
        set
        {
            this._format = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute("base", AttributeName="base1")]
    [System.ComponentModel.DefaultValueAttribute("10")]
    public string Base1
    {
        get
        {
            return this._base1;
        }
        set
        {
            this._base1 = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="index")]
    public string Index
    {
        get
        {
            return this._index;
        }
        set
        {
            this._index = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="powerForm")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool PowerForm
    {
        get
        {
            return this._powerForm;
        }
        set
        {
            this._powerForm = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="field")]
    public string Field
    {
        get
        {
            return this._field;
        }
        set
        {
            this._field = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="delimiter")]
    [System.ComponentModel.DefaultValueAttribute(";")]
    public string Delimiter
    {
        get
        {
            return this._delimiter;
        }
        set
        {
            this._delimiter = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="mappingIndicator")]
    [System.ComponentModel.DefaultValueAttribute("=")]
    public string MappingIndicator
    {
        get
        {
            return this._mappingIndicator;
        }
        set
        {
            this._mappingIndicator = value;
        }
    }
}
}
#pragma warning restore
