// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="QTIMetadata.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("qtiMetadata", Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p1", IsNullable=false)]
public partial class QTIMetadataType
{
    
    #region Private fields
    private bool _itemTemplate;
    
    private bool _timeDependent;
    
    private bool _composite;
    
    private List<QTIMetadataTypeInteractionType> _interactionType;
    
    private QTIMetadataTypeFeedbackType _feedbackType;
    
    private bool _solutionAvailable;
    
    private string _toolName;
    
    private string _toolVersion;
    
    private string _toolVendor;
    #endregion
    
    public QTIMetadataType()
    {
        this._interactionType = new List<QTIMetadataTypeInteractionType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("itemTemplate")]
    public bool ItemTemplate
    {
        get
        {
            return this._itemTemplate;
        }
        set
        {
            this._itemTemplate = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("timeDependent")]
    public bool TimeDependent
    {
        get
        {
            return this._timeDependent;
        }
        set
        {
            this._timeDependent = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("composite")]
    public bool Composite
    {
        get
        {
            return this._composite;
        }
        set
        {
            this._composite = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("interactionType", ElementName="interactionType")]
    public List<QTIMetadataTypeInteractionType> InteractionType
    {
        get
        {
            return this._interactionType;
        }
        set
        {
            this._interactionType = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("feedbackType")]
    public QTIMetadataTypeFeedbackType FeedbackType
    {
        get
        {
            return this._feedbackType;
        }
        set
        {
            this._feedbackType = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("solutionAvailable")]
    public bool SolutionAvailable
    {
        get
        {
            return this._solutionAvailable;
        }
        set
        {
            this._solutionAvailable = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("toolName")]
    public string ToolName
    {
        get
        {
            return this._toolName;
        }
        set
        {
            this._toolName = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("toolVersion")]
    public string ToolVersion
    {
        get
        {
            return this._toolVersion;
        }
        set
        {
            this._toolVersion = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("toolVendor")]
    public string ToolVendor
    {
        get
        {
            return this._toolVendor;
        }
        set
        {
            this._toolVendor = value;
        }
    }
}
}
#pragma warning restore
