// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="RandomFloat.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("randomFloat", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class RandomFloatType : EmptyPrimitiveTypeType
{
    
    #region Private fields
    private string _min;
    
    private string _max;
    #endregion
    
    public RandomFloatType()
    {
        this._min = "0";
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="min")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string Min
    {
        get
        {
            return this._min;
        }
        set
        {
            this._min = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="max")]
    public string Max
    {
        get
        {
            return this._max;
        }
        set
        {
            this._max = value;
        }
    }
}
}
#pragma warning restore
