// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ResponseDeclaration.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("responseDeclaration", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class ResponseDeclarationType
{
    
    #region Private fields
    private DefaultValueType _defaultValue;
    
    private CorrectResponseType _correctResponse;
    
    private MappingType _mapping;
    
    private AreaMappingType _areaMapping;
    
    private string _identifier;
    
    private ResponseDeclarationTypeCardinality _cardinality;
    
    private ResponseDeclarationTypeBaseType _baseType;
    #endregion
    
    public ResponseDeclarationType()
    {
        this._areaMapping = new AreaMappingType();
        this._mapping = new MappingType();
        this._correctResponse = new CorrectResponseType();
        this._defaultValue = new DefaultValueType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("defaultValue")]
    public DefaultValueType DefaultValue
    {
        get
        {
            return this._defaultValue;
        }
        set
        {
            this._defaultValue = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("correctResponse")]
    public CorrectResponseType CorrectResponse
    {
        get
        {
            return this._correctResponse;
        }
        set
        {
            this._correctResponse = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("mapping")]
    public MappingType Mapping
    {
        get
        {
            return this._mapping;
        }
        set
        {
            this._mapping = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("areaMapping")]
    public AreaMappingType AreaMapping
    {
        get
        {
            return this._areaMapping;
        }
        set
        {
            this._areaMapping = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="cardinality")]
    public ResponseDeclarationTypeCardinality Cardinality
    {
        get
        {
            return this._cardinality;
        }
        set
        {
            this._cardinality = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="baseType")]
    public ResponseDeclarationTypeBaseType BaseType
    {
        get
        {
            return this._baseType;
        }
        set
        {
            this._baseType = value;
        }
    }
}
}
#pragma warning restore
