// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Scaffold.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("ScaffoldType")]
public partial class ScaffoldType
{
    
    #region Private fields
    private string _revealOrder;
    
    private ScaffoldBehaviorType _scaffoldBehavior;
    #endregion
    
    public ScaffoldType()
    {
        this._scaffoldBehavior = new ScaffoldBehaviorType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="revealOrder")]
    public string RevealOrder
    {
        get
        {
            return this._revealOrder;
        }
        set
        {
            this._revealOrder = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("scaffoldBehavior")]
    public ScaffoldBehaviorType ScaffoldBehavior
    {
        get
        {
            return this._scaffoldBehavior;
        }
        set
        {
            this._scaffoldBehavior = value;
        }
    }
}
}
#pragma warning restore
