// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SignFile.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("SignFileType")]
public partial class SignFileType
{
    
    #region Private fields
    private VideoFileInfoType _videoFileInfo;
    
    private ObjectFileInfoType _boneAnimationVideoFile;
    #endregion
    
    public SignFileType()
    {
        this._boneAnimationVideoFile = new ObjectFileInfoType();
        this._videoFileInfo = new VideoFileInfoType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("videoFileInfo")]
    public VideoFileInfoType VideoFileInfo
    {
        get
        {
            return this._videoFileInfo;
        }
        set
        {
            this._videoFileInfo = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("boneAnimationVideoFile")]
    public ObjectFileInfoType BoneAnimationVideoFile
    {
        get
        {
            return this._boneAnimationVideoFile;
        }
        set
        {
            this._boneAnimationVideoFile = value;
        }
    }
}
}
#pragma warning restore
