// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Signing.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("SigningType")]
public partial class SigningType
{
    
    #region Private fields
    private SignFileType _signFileASL;
    
    private SignFileType _signFileSignedEnglish;
    #endregion
    
    public SigningType()
    {
        this._signFileSignedEnglish = new SignFileType();
        this._signFileASL = new SignFileType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("signFileASL")]
    public SignFileType SignFileASL
    {
        get
        {
            return this._signFileASL;
        }
        set
        {
            this._signFileASL = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("signFileSignedEnglish")]
    public SignFileType SignFileSignedEnglish
    {
        get
        {
            return this._signFileSignedEnglish;
        }
        set
        {
            this._signFileSignedEnglish = value;
        }
    }
}
}
#pragma warning restore
