// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TactileFile.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("TactileFileType")]
public partial class TactileFileType
{
    
    #region Private fields
    private AudioFileInfoType _tactileAudioFile;
    
    private LabelledStringType _tactileAudioText;
    
    private LabelledStringType _tactileBrailleText;
    #endregion
    
    public TactileFileType()
    {
        this._tactileBrailleText = new LabelledStringType();
        this._tactileAudioText = new LabelledStringType();
        this._tactileAudioFile = new AudioFileInfoType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("tactileAudioFile")]
    public AudioFileInfoType TactileAudioFile
    {
        get
        {
            return this._tactileAudioFile;
        }
        set
        {
            this._tactileAudioFile = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("tactileAudioText")]
    public LabelledStringType TactileAudioText
    {
        get
        {
            return this._tactileAudioText;
        }
        set
        {
            this._tactileAudioText = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("tactileBrailleText")]
    public LabelledStringType TactileBrailleText
    {
        get
        {
            return this._tactileBrailleText;
        }
        set
        {
            this._tactileBrailleText = value;
        }
    }
}
}
#pragma warning restore
