// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TDH.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("td", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class TDHType
{
    
    #region Private fields
    private object[] _items;
    
    private ItemsChoiceType18[] _itemsElementName;
    
    private List<string> _text;
    
    private string _id;
    
    private List<string> _class;
    
    private string _lang;
    
    private string _label;
    
    private string _headers;
    
    private TDHTypeScope _scope;
    
    private string _abbr;
    
    private string _axis;
    
    private int _rowspan;
    
    private int _colspan;
    
    private TDHTypeAlign _align;
    
    private TDHTypeValign _valign;
    #endregion
    
    public TDHType()
    {
        this._class = new List<string>();
        this._text = new List<string>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("a", typeof(AType))]
    [System.Xml.Serialization.XmlElementAttribute("abbr", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("acronym", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("address", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("associateInteraction", typeof(AssociateInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("big", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("blockquote", typeof(BlockQuoteType))]
    [System.Xml.Serialization.XmlElementAttribute("br", typeof(BRType))]
    [System.Xml.Serialization.XmlElementAttribute("choiceInteraction", typeof(ChoiceInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("cite", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("code", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("customInteraction", typeof(CustomInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("dfn", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("div", typeof(DivType))]
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(DLType))]
    [System.Xml.Serialization.XmlElementAttribute("drawingInteraction", typeof(DrawingInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("endAttemptInteraction", typeof(EndAttemptInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("extendedTextInteraction", typeof(ExtendedTextInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("feedbackBlock", typeof(FeedbackBlockType))]
    [System.Xml.Serialization.XmlElementAttribute("feedbackInline", typeof(FeedbackInlineType))]
    [System.Xml.Serialization.XmlElementAttribute("gapMatchInteraction", typeof(GapMatchInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("graphicAssociateInteraction", typeof(GraphicAssociateInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("graphicGapMatchInteraction", typeof(GraphicGapMatchInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("graphicOrderInteraction", typeof(GraphicOrderInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("h1", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("h2", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("h3", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("h4", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("h5", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("h6", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("hotspotInteraction", typeof(HotspotInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("hottext", typeof(HotTextType))]
    [System.Xml.Serialization.XmlElementAttribute("hottextInteraction", typeof(HotTextInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("hr", typeof(HRType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("img", typeof(ImgType))]
    [System.Xml.Serialization.XmlElementAttribute("inlineChoiceInteraction", typeof(InlineChoiceInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("kbd", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("matchInteraction", typeof(MatchInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("mediaInteraction", typeof(MediaInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("object", typeof(ObjectType))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(OULType))]
    [System.Xml.Serialization.XmlElementAttribute("orderInteraction", typeof(OrderInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("pre", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("printedVariable", typeof(PrintedVariableType))]
    [System.Xml.Serialization.XmlElementAttribute("q", typeof(QType))]
    [System.Xml.Serialization.XmlElementAttribute("samp", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("selectPointInteraction", typeof(SelectPointInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("sliderInteraction", typeof(SliderInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("small", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("span", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(TableType))]
    [System.Xml.Serialization.XmlElementAttribute("templateBlock", typeof(TemplateBlockType))]
    [System.Xml.Serialization.XmlElementAttribute("templateInline", typeof(TemplateInlineType))]
    [System.Xml.Serialization.XmlElementAttribute("textEntryInteraction", typeof(TextEntryInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(OULType))]
    [System.Xml.Serialization.XmlElementAttribute("uploadInteraction", typeof(UploadInteractionType))]
    [System.Xml.Serialization.XmlElementAttribute("var", typeof(HTMLTextType))]
    [System.Xml.Serialization.XmlElementAttribute("math", typeof(Mathtype), Namespace="http://www.w3.org/1998/Math/MathML")]
    [System.Xml.Serialization.XmlElementAttribute("include", typeof(IncludeType), Namespace="http://www.w3.org/2001/XInclude")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this._items;
        }
        set
        {
            this._items = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType18[] ItemsElementName
    {
        get
        {
            return this._itemsElementName;
        }
        set
        {
            this._itemsElementName = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public List<string> Text
    {
        get
        {
            return this._text;
        }
        set
        {
            this._text = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="id")]
    public string Id
    {
        get
        {
            return this._id;
        }
        set
        {
            this._id = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
    public List<string> Class
    {
        get
        {
            return this._class;
        }
        set
        {
            this._class = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
    public string Lang
    {
        get
        {
            return this._lang;
        }
        set
        {
            this._lang = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="label")]
    public string Label
    {
        get
        {
            return this._label;
        }
        set
        {
            this._label = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="headers")]
    public string Headers
    {
        get
        {
            return this._headers;
        }
        set
        {
            this._headers = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="scope")]
    public TDHTypeScope Scope
    {
        get
        {
            return this._scope;
        }
        set
        {
            this._scope = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="abbr")]
    public string Abbr
    {
        get
        {
            return this._abbr;
        }
        set
        {
            this._abbr = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="axis")]
    public string Axis
    {
        get
        {
            return this._axis;
        }
        set
        {
            this._axis = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="rowspan")]
    public int Rowspan
    {
        get
        {
            return this._rowspan;
        }
        set
        {
            this._rowspan = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="colspan")]
    public int Colspan
    {
        get
        {
            return this._colspan;
        }
        set
        {
            this._colspan = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="align")]
    public TDHTypeAlign Align
    {
        get
        {
            return this._align;
        }
        set
        {
            this._align = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="valign")]
    public TDHTypeValign Valign
    {
        get
        {
            return this._valign;
        }
        set
        {
            this._valign = value;
        }
    }
}
}
#pragma warning restore
