// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("TemplateDeclarationTypeBaseType")]
public enum TemplateDeclarationTypeBaseType
{
    
    /// <remarks/>
    boolean,
    
    /// <remarks/>
    directedPair,
    
    /// <remarks/>
    duration,
    
    /// <remarks/>
    file,
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    identifier,
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    pair,
    
    /// <remarks/>
    point,
    
    /// <remarks/>
    @string,
    
    /// <remarks/>
    uri,
}
}
#pragma warning restore
