// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TestPart.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1")]
[System.Xml.Serialization.XmlRootAttribute("testPart", Namespace="http://www.imsglobal.org/xsd/imsqti_v2p1", IsNullable=false)]
public partial class TestPartType
{
    
    #region Private fields
    private List<LogicSingleType> _preCondition;
    
    private List<BranchRuleType> _branchRule;
    
    private ItemSessionControlType _itemSessionControl;
    
    private TimeLimitsType _timeLimits;
    
    private List<object> _items;
    
    private List<TestFeedbackType> _testFeedback;
    
    private string _identifier;
    
    private TestPartTypeNavigationMode _navigationMode;
    
    private TestPartTypeSubmissionMode _submissionMode;
    #endregion
    
    public TestPartType()
    {
        this._testFeedback = new List<TestFeedbackType>();
        this._items = new List<object>();
        this._timeLimits = new TimeLimitsType();
        this._itemSessionControl = new ItemSessionControlType();
        this._branchRule = new List<BranchRuleType>();
        this._preCondition = new List<LogicSingleType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("preCondition", ElementName="preCondition")]
    public List<LogicSingleType> PreCondition
    {
        get
        {
            return this._preCondition;
        }
        set
        {
            this._preCondition = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("branchRule", ElementName="branchRule")]
    public List<BranchRuleType> BranchRule
    {
        get
        {
            return this._branchRule;
        }
        set
        {
            this._branchRule = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("itemSessionControl")]
    public ItemSessionControlType ItemSessionControl
    {
        get
        {
            return this._itemSessionControl;
        }
        set
        {
            this._itemSessionControl = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("timeLimits")]
    public TimeLimitsType TimeLimits
    {
        get
        {
            return this._timeLimits;
        }
        set
        {
            this._timeLimits = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("assessmentSection", typeof(AssessmentSectionType))]
    [System.Xml.Serialization.XmlElementAttribute("assessmentSectionRef", typeof(AssessmentSectionRefType))]
    public List<object> Items
    {
        get
        {
            return this._items;
        }
        set
        {
            this._items = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("testFeedback", ElementName="testFeedback")]
    public List<TestFeedbackType> TestFeedback
    {
        get
        {
            return this._testFeedback;
        }
        set
        {
            this._testFeedback = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="navigationMode")]
    public TestPartTypeNavigationMode NavigationMode
    {
        get
        {
            return this._navigationMode;
        }
        set
        {
            this._navigationMode = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="submissionMode")]
    public TestPartTypeSubmissionMode SubmissionMode
    {
        get
        {
            return this._submissionMode;
        }
        set
        {
            this._submissionMode = value;
        }
    }
}
}
#pragma warning restore
