// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TextLink.Type", Namespace="http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0")]
[System.Xml.Serialization.XmlRootAttribute("TextLinkType")]
public partial class TextLinkType
{
    
    #region Private fields
    private object _item;
    
    private ItemChoiceType9 _itemElementName;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute("characterLink", typeof(string), DataType="integer")]
    [System.Xml.Serialization.XmlElementAttribute("characterStringLink", typeof(CharacterStringLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("fullString", typeof(EmptyPrimitiveTypeType1))]
    [System.Xml.Serialization.XmlElementAttribute("wordLink", typeof(string), DataType="integer")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType9 ItemElementName
    {
        get
        {
            return this._itemElementName;
        }
        set
        {
            this._itemElementName = value;
        }
    }
}
}
#pragma warning restore
