// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="AssessmentResult.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_result_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("assessmentResult", Namespace="http://www.imsglobal.org/xsd/imsqti_result_v2p2", IsNullable=false)]
public partial class AssessmentResultType
{
    
    #region Private fields
    private ContextType _context;
    
    private TestResultType _testResult;
    
    private List<ItemResultType> _itemResult;
    #endregion
    
    public AssessmentResultType()
    {
        this._itemResult = new List<ItemResultType>();
        this._testResult = new TestResultType();
        this._context = new ContextType();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("context")]
    public ContextType Context
    {
        get
        {
            return this._context;
        }
        set
        {
            this._context = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("testResult")]
    public TestResultType TestResult
    {
        get
        {
            return this._testResult;
        }
        set
        {
            this._testResult = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("itemResult", ElementName="itemResult")]
    public List<ItemResultType> ItemResult
    {
        get
        {
            return this._itemResult;
        }
        set
        {
            this._itemResult = value;
        }
    }
}
}
#pragma warning restore
