// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetObjectType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MapEntryType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="EmptyPrimitiveType.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("EmptyPrimitiveTypeType")]
public partial class EmptyPrimitiveTypeType
{
}
}
#pragma warning restore
