// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_2
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrdinaryStatistic.Type", Namespace = "http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
    [System.Xml.Serialization.XmlRootAttribute("OrdinaryStatisticType")]
    public partial class OrdinaryStatisticType
    {

        #region Private fields
        private List<TargetObjectType> _targetObject;

        private ValueType _value;

        private string _name;

        private string _glossary;

        private string _context;

        private string _caseCount;

        private double _stdError;

        private double _stdDeviation;

        private System.DateTime _lastUpdated;
        #endregion

        public OrdinaryStatisticType()
        {
            this._value = new ValueType();
            this._targetObject = new List<TargetObjectType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("targetObject", ElementName = "targetObject")]
        public List<TargetObjectType> TargetObject
        {
            get
            {
                return this._targetObject;
            }
            set
            {
                this._targetObject = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("value")]
        public ValueType Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName", AttributeName = "name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI", AttributeName = "glossary")]
        public string Glossary
        {
            get
            {
                return this._glossary;
            }
            set
            {
                this._glossary = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI", AttributeName = "context")]
        public string Context
        {
            get
            {
                return this._context;
            }
            set
            {
                this._context = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer", AttributeName = "caseCount")]
        public string CaseCount
        {
            get
            {
                return this._caseCount;
            }
            set
            {
                this._caseCount = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "stdError")]
        public double StdError
        {
            get
            {
                return this._stdError;
            }
            set
            {
                this._stdError = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "stdDeviation")]
        public double StdDeviation
        {
            get
            {
                return this._stdDeviation;
            }
            set
            {
                this._stdDeviation = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date", AttributeName = "lastUpdated")]
        public System.DateTime LastUpdated
        {
            get
            {
                return this._lastUpdated;
            }
            set
            {
                this._lastUpdated = value;
            }
        }
    }
}
#pragma warning restore
