// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="OutcomeVariable.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_result_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("OutcomeVariableType")]
public partial class OutcomeVariableType
{
    
    #region Private fields
    private List<ValueType> _value;
    
    private string _identifier;
    
    private OutcomeVariableTypeCardinality _cardinality;
    
    private OutcomeVariableTypeBaseType _baseType;
    
    private List<ViewType> _view;
    
    private string _interpretation;
    
    private string _longInterpretation;
    
    private double _normalMaximum;
    
    private double _normalMinimum;
    
    private double _masteryValue;
    #endregion
    
    public OutcomeVariableType()
    {
        this._view = new List<ViewType>();
        this._value = new List<ValueType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("value", ElementName="value")]
    public List<ValueType> Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="cardinality")]
    public OutcomeVariableTypeCardinality Cardinality
    {
        get
        {
            return this._cardinality;
        }
        set
        {
            this._cardinality = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="baseType")]
    public OutcomeVariableTypeBaseType BaseType
    {
        get
        {
            return this._baseType;
        }
        set
        {
            this._baseType = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="view")]
    public List<ViewType> View
    {
        get
        {
            return this._view;
        }
        set
        {
            this._view = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="interpretation")]
    public string Interpretation
    {
        get
        {
            return this._interpretation;
        }
        set
        {
            this._interpretation = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="longInterpretation")]
    public string LongInterpretation
    {
        get
        {
            return this._longInterpretation;
        }
        set
        {
            this._longInterpretation = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="normalMaximum")]
    public double NormalMaximum
    {
        get
        {
            return this._normalMaximum;
        }
        set
        {
            this._normalMaximum = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="normalMinimum")]
    public double NormalMinimum
    {
        get
        {
            return this._normalMinimum;
        }
        set
        {
            this._normalMinimum = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="masteryValue")]
    public double MasteryValue
    {
        get
        {
            return this._masteryValue;
        }
        set
        {
            this._masteryValue = value;
        }
    }
}
}
#pragma warning restore
