// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("QTIMetadataTypeInteractionType")]
public enum QTIMetadataTypeInteractionType
{
    
    /// <remarks/>
    associateInteraction,
    
    /// <remarks/>
    choiceInteraction,
    
    /// <remarks/>
    customInteraction,
    
    /// <remarks/>
    drawingInteraction,
    
    /// <remarks/>
    endAttemptInteraction,
    
    /// <remarks/>
    extendedTextInteraction,
    
    /// <remarks/>
    gapMatchInteraction,
    
    /// <remarks/>
    graphicAssociateInteraction,
    
    /// <remarks/>
    graphicGapMatchInteraction,
    
    /// <remarks/>
    graphicOrderInteraction,
    
    /// <remarks/>
    hotspotInteraction,
    
    /// <remarks/>
    hottextInteraction,
    
    /// <remarks/>
    inlineChoiceInteraction,
    
    /// <remarks/>
    matchInteraction,
    
    /// <remarks/>
    mediaInteraction,
    
    /// <remarks/>
    orderInteraction,
    
    /// <remarks/>
    positionObjectInteraction,
    
    /// <remarks/>
    selectPointInteraction,
    
    /// <remarks/>
    sliderInteraction,
    
    /// <remarks/>
    textEntryInteraction,
    
    /// <remarks/>
    uploadInteraction,
}
}
#pragma warning restore
