// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v2_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Value.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("ValueType")]
public partial class ValueType
{
    
    #region Private fields
    private string _fieldIdentifier;
    
    private ValueTypeBaseType _baseType;
    
    private string _value;
    #endregion
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName", AttributeName="fieldIdentifier")]
    public string FieldIdentifier
    {
        get
        {
            return this._fieldIdentifier;
        }
        set
        {
            this._fieldIdentifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="baseType")]
    public ValueTypeBaseType BaseType
    {
        get
        {
            return this._baseType;
        }
        set
        {
            this._baseType = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
