// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CartridgeToolLocator.Type", Namespace="http://www.imsglobal.org/xsd/imslticc_v1p0")]
[System.Xml.Serialization.XmlRootAttribute("lti_tool_locator", Namespace="http://www.imsglobal.org/xsd/imslticc_v1p0", IsNullable=false)]
public partial class CartridgeToolLocatorType : ToolLocatorType
{
    
    #region Private fields
    private List<PropertyType> _tool_settings;
    
    private List<System.Xml.XmlElement> _any;
    #endregion
    
    public CartridgeToolLocatorType()
    {
        this._any = new List<System.Xml.XmlElement>();
        this._tool_settings = new List<PropertyType>();
    }
    
    [System.Xml.Serialization.XmlArrayItemAttribute("property", Namespace="http://www.imsglobal.org/xsd/imslticm_v1p0", IsNullable=false, ElementName="tool_settings")]
    public List<PropertyType> Tool_settings
    {
        get
        {
            return this._tool_settings;
        }
        set
        {
            this._tool_settings = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public List<System.Xml.XmlElement> Any
    {
        get
        {
            return this._any;
        }
        set
        {
            this._any = value;
        }
    }
}
}
#pragma warning restore
