// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest")]
[System.Xml.Serialization.XmlRootAttribute("KindTypeValue")]
public enum KindTypeValue
{
    
    /// <remarks/>
    ispartof,
    
    /// <remarks/>
    haspart,
    
    /// <remarks/>
    isversionof,
    
    /// <remarks/>
    hasversion,
    
    /// <remarks/>
    isformatof,
    
    /// <remarks/>
    hasformat,
    
    /// <remarks/>
    references,
    
    /// <remarks/>
    isreferencedby,
    
    /// <remarks/>
    isbasedon,
    
    /// <remarks/>
    isbasisfor,
    
    /// <remarks/>
    requires,
    
    /// <remarks/>
    isrequiredby,
}
}
#pragma warning restore
