// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LifeCycle.Type", Namespace="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest")]
[System.Xml.Serialization.XmlRootAttribute("LifeCycleType")]
public partial class LifeCycleType
{
    
    #region Private fields
    private object[][] _contribute;
    #endregion
    
    [System.Xml.Serialization.XmlArrayItemAttribute("date", typeof(DateTimeType), IsNullable=false, ElementName="contribute")]
    [System.Xml.Serialization.XmlArrayItemAttribute("entity", typeof(string), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("role", typeof(RoleLifeCycleType), IsNullable=false)]
    public List<object> Contribute
    {
        get
        {
            return this._contribute;
        }
        set
        {
            this._contribute = value;
        }
    }
}
}
#pragma warning restore
