// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "PlatformPropertySet.Type", Namespace = "http://www.imsglobal.org/xsd/imslticm_v1p0")]
    [System.Xml.Serialization.XmlRootAttribute("PlatformPropertySetType")]
    public partial class PlatformPropertySetType : PropertySetType
    {

        #region Private fields
        private string _platform;

        private List<System.Xml.XmlAttribute> _anyAttr;
        #endregion

        public PlatformPropertySetType()
        {
            this._anyAttr = new List<System.Xml.XmlAttribute>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "Name", AttributeName = "platform")]
        public string Platform
        {
            get
            {
                return this._platform;
            }
            set
            {
                this._platform = value;
            }
        }

        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public List<System.Xml.XmlAttribute> AnyAttr
        {
            get
            {
                return this._anyAttr;
            }
            set
            {
                this._anyAttr = value;
            }
        }
    }
}
#pragma warning restore
