// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Resources.Type", Namespace="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1")]
[System.Xml.Serialization.XmlRootAttribute("ResourcesType")]
public partial class ResourcesType
{
    
    #region Private fields
    private List<ResourceType1> _resource;
    
    private string _base;
    #endregion
    
    public ResourcesType()
    {
        this._resource = new List<ResourceType1>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("resource", ElementName="resource")]
    public List<ResourceType1> Resource
    {
        get
        {
            return this._resource;
        }
        set
        {
            this._resource = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="base")]
    public string Base
    {
        get
        {
            return this._base;
        }
        set
        {
            this._base = value;
        }
    }
}
}
#pragma warning restore
