// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1")]
[System.Xml.Serialization.XmlRootAttribute("ResourceTypeType")]
public enum ResourceTypeType
{
    
    /// <remarks/>
    webcontent,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("imsqti_xmlv1p2/imscc_xmlv1p1/assessment")]
    imsqti_xmlv1p2imscc_xmlv1p1assessment,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("imsqti_xmlv1p2/imscc_xmlv1p1/question-bank")]
    imsqti_xmlv1p2imscc_xmlv1p1questionbank,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("associatedcontent/imscc_xmlv1p1/learning-application-resource")]
    associatedcontentimscc_xmlv1p1learningapplicationresource,
    
    /// <remarks/>
    imsdt_xmlv1p1,
    
    /// <remarks/>
    imswl_xmlv1p1,
    
    /// <remarks/>
    imsbasiclti_xmlv1p0,
}
}
#pragma warning restore
