// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_1
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TaxonPath.Type", Namespace="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest")]
[System.Xml.Serialization.XmlRootAttribute("TaxonPathType")]
public partial class TaxonPathType
{
    
    #region Private fields
    private object[] _taxon;
    #endregion
    
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(LangStringType), IsNullable=false, ElementName="taxon")]
    [System.Xml.Serialization.XmlArrayItemAttribute("id", typeof(string), IsNullable=false)]
    public List<object> Taxon
    {
        get
        {
            return this._taxon;
        }
        set
        {
            this._taxon = value;
        }
    }
}
}
#pragma warning restore
