// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_0
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Icon.Type", Namespace="http://www.imsglobal.org/xsd/imslticp_v1p0")]
[System.Xml.Serialization.XmlRootAttribute("IconType")]
public partial class IconType
{
    
    #region Private fields
    private string _key;
    
    private string _platform;
    
    private string _style;
    
    private List<System.Xml.XmlAttribute> _anyAttr;
    
    private string _value;
    #endregion
    
    public IconType()
    {
        this._anyAttr = new List<System.Xml.XmlAttribute>();
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="Name", AttributeName="key")]
    public string Key
    {
        get
        {
            return this._key;
        }
        set
        {
            this._key = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="Name", AttributeName="platform")]
    public string Platform
    {
        get
        {
            return this._platform;
        }
        set
        {
            this._platform = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="Name", AttributeName="style")]
    public string Style
    {
        get
        {
            return this._style;
        }
        set
        {
            this._style = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public List<System.Xml.XmlAttribute> AnyAttr
    {
        get
        {
            return this._anyAttr;
        }
        set
        {
            this._anyAttr = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
}
#pragma warning restore
