// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_0
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Item.Type", Namespace="http://www.imsglobal.org/xsd/imscp_v1p1")]
[System.Xml.Serialization.XmlRootAttribute("ItemType")]
public partial class ItemType
{
    
    #region Private fields
    private string _title;
    
    private List<ItemType> _item;
    
    private MetadataType _metadata;
    
    private List<System.Xml.XmlElement> _any;
    
    private string _identifier;
    
    private string _identifierref;
    
    private bool _isvisible;
    
    private string _parameters;
    
    private List<System.Xml.XmlAttribute> _anyAttr;
    #endregion
    
    public ItemType()
    {
        this._anyAttr = new List<System.Xml.XmlAttribute>();
        this._any = new List<System.Xml.XmlElement>();
        this._metadata = new MetadataType();
        this._item = new List<ItemType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("title")]
    public string Title
    {
        get
        {
            return this._title;
        }
        set
        {
            this._title = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("item", ElementName="item")]
    public List<ItemType> Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("metadata")]
    public MetadataType Metadata
    {
        get
        {
            return this._metadata;
        }
        set
        {
            this._metadata = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public List<System.Xml.XmlElement> Any
    {
        get
        {
            return this._any;
        }
        set
        {
            this._any = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="identifierref")]
    public string Identifierref
    {
        get
        {
            return this._identifierref;
        }
        set
        {
            this._identifierref = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="isvisible")]
    public bool Isvisible
    {
        get
        {
            return this._isvisible;
        }
        set
        {
            this._isvisible = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="parameters")]
    public string Parameters
    {
        get
        {
            return this._parameters;
        }
        set
        {
            this._parameters = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public List<System.Xml.XmlAttribute> AnyAttr
    {
        get
        {
            return this._anyAttr;
        }
        set
        {
            this._anyAttr = value;
        }
    }
}
}
#pragma warning restore
