// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Authorizations.Type", Namespace="http://www.imsglobal.org/xsd/imsccv1p2/imsccauth_v1p2")]
[System.Xml.Serialization.XmlRootAttribute("AuthorizationsType")]
public partial class AuthorizationsType
{
    
    #region Private fields
    private AuthorizationType _authorization;
    
    private List<System.Xml.XmlElement> _any;
    
    private AuthorizationsTypeAccess _access;
    
    private bool _import;
    #endregion
    
    public AuthorizationsType()
    {
        this._any = new List<System.Xml.XmlElement>();
        this._authorization = new AuthorizationType();
        this._import = false;
    }
    
    [System.Xml.Serialization.XmlElementAttribute("authorization")]
    public AuthorizationType Authorization
    {
        get
        {
            return this._authorization;
        }
        set
        {
            this._authorization = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public List<System.Xml.XmlElement> Any
    {
        get
        {
            return this._any;
        }
        set
        {
            this._any = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="access")]
    public AuthorizationsTypeAccess Access
    {
        get
        {
            return this._access;
        }
        set
        {
            this._access = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="import")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Import
    {
        get
        {
            return this._import;
        }
        set
        {
            this._import = value;
        }
    }
}
}
#pragma warning restore
