// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Dependency.Type", Namespace="http://www.imsglobal.org/xsd/imsccv1p2/imscp_v1p1")]
[System.Xml.Serialization.XmlRootAttribute("DependencyType")]
public partial class DependencyType
{
    
    #region Private fields
    private string _identifierref;
    #endregion
    
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="identifierref")]
    public string Identifierref
    {
        get
        {
            return this._identifierref;
        }
        set
        {
            this._identifierref = value;
        }
    }
}
}
#pragma warning restore
