// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ItemOrg.Type", Namespace="http://www.imsglobal.org/xsd/imsccv1p2/imscp_v1p1")]
[System.Xml.Serialization.XmlRootAttribute("ItemOrgType")]
public partial class ItemOrgType
{
    
    #region Private fields
    private List<ItemType> _item;
    
    private MetadataType _metadata;
    
    private string _identifier;
    #endregion
    
    public ItemOrgType()
    {
        this._metadata = new MetadataType();
        this._item = new List<ItemType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("item", ElementName="item")]
    public List<ItemType> Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("metadata")]
    public MetadataType Metadata
    {
        get
        {
            return this._metadata;
        }
        set
        {
            this._metadata = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="identifier")]
    public string Identifier
    {
        get
        {
            return this._identifier;
        }
        set
        {
            this._identifier = value;
        }
    }
}
}
#pragma warning restore
