// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/imsccv1p2/LOM/manifest", IncludeInSchema=false)]
[System.Xml.Serialization.XmlRootAttribute("ItemsChoiceType3")]
public enum ItemsChoiceType3
{
    
    /// <remarks/>
    classification,
    
    /// <remarks/>
    educational,
    
    /// <remarks/>
    general,
    
    /// <remarks/>
    lifeCycle,
    
    /// <remarks/>
    relation,
    
    /// <remarks/>
    rights,
    
    /// <remarks/>
    technical,
}
}
#pragma warning restore
