// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ltsc.ieee.org/xsd/imsccv1p2/LOM/manifest")]
[System.Xml.Serialization.XmlRootAttribute("PurposeTypeValue")]
public enum PurposeTypeValue
{
    
    /// <remarks/>
    discipline,
    
    /// <remarks/>
    idea,
    
    /// <remarks/>
    prerequisite,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("educational objective")]
    educationalobjective,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("accessibility restrictions")]
    accessibilityrestrictions,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("educational level")]
    educationallevel,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("skill level")]
    skilllevel,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("security level")]
    securitylevel,
    
    /// <remarks/>
    competency,
}
}
#pragma warning restore
