// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_3
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.Xml.Serialization.XmlIncludeAttribute(typeof(CartridgeBasicLTILinkType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="BasicLTILink.Type", Namespace="http://www.imsglobal.org/xsd/imsbasiclti_v1p0")]
[System.Xml.Serialization.XmlRootAttribute("BasicLTILinkType")]
public partial class BasicLTILinkType
{
    
    #region Private fields
    private string _title;
    
    private string _description;
    
    private List<PropertyType> _custom;
    
    private PlatformPropertySetType _extensions;
    
    private string _launch_url;
    
    private string _secure_launch_url;
    
    private IconType _icon;
    
    private IconType _secure_icon;
    
    private VendorType _vendor;
    #endregion
    
    public BasicLTILinkType()
    {
        this._vendor = new VendorType();
        this._secure_icon = new IconType();
        this._icon = new IconType();
        this._extensions = new PlatformPropertySetType();
        this._custom = new List<PropertyType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", ElementName="title")]
    public string Title
    {
        get
        {
            return this._title;
        }
        set
        {
            this._title = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("description")]
    public string Description
    {
        get
        {
            return this._description;
        }
        set
        {
            this._description = value;
        }
    }
    
    [System.Xml.Serialization.XmlArrayItemAttribute("property", Namespace="http://www.imsglobal.org/xsd/imslticm_v1p0", IsNullable=false, ElementName="custom")]
    public List<PropertyType> Custom
    {
        get
        {
            return this._custom;
        }
        set
        {
            this._custom = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("extensions")]
    public PlatformPropertySetType Extensions
    {
        get
        {
            return this._extensions;
        }
        set
        {
            this._extensions = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("launch_url")]
    public string Launch_url
    {
        get
        {
            return this._launch_url;
        }
        set
        {
            this._launch_url = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("secure_launch_url")]
    public string Secure_launch_url
    {
        get
        {
            return this._secure_launch_url;
        }
        set
        {
            this._secure_launch_url = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("icon")]
    public IconType Icon
    {
        get
        {
            return this._icon;
        }
        set
        {
            this._icon = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("secure_icon")]
    public IconType Secure_icon
    {
        get
        {
            return this._secure_icon;
        }
        set
        {
            this._secure_icon = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("vendor")]
    public VendorType Vendor
    {
        get
        {
            return this._vendor;
        }
        set
        {
            this._vendor = value;
        }
    }
}
}
#pragma warning restore
