// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_3
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CurriculumStandardsMetadata.Type", Namespace="http://www.imsglobal.org/xsd/imsccv1p3/imscsmd_v1p0")]
[System.Xml.Serialization.XmlRootAttribute("CurriculumStandardsMetadataType")]
public partial class CurriculumStandardsMetadataType
{
    
    #region Private fields
    private List<SetOfGUIDsType> _setOfGUIDs;
    
    private string _providerId;
    #endregion
    
    public CurriculumStandardsMetadataType()
    {
        this._setOfGUIDs = new List<SetOfGUIDsType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("setOfGUIDs", ElementName="setOfGUIDs")]
    public List<SetOfGUIDsType> SetOfGUIDs
    {
        get
        {
            return this._setOfGUIDs;
        }
        set
        {
            this._setOfGUIDs = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="providerId")]
    public string ProviderId
    {
        get
        {
            return this._providerId;
        }
        set
        {
            this._providerId = value;
        }
    }
}
}
#pragma warning restore
