// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_3
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/imsccv1p3/LOM/manifest", IncludeInSchema=false)]
[System.Xml.Serialization.XmlRootAttribute("ItemsChoiceType23")]
public enum ItemsChoiceType23
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}
}
#pragma warning restore
