// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_3
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LOM.Type", Namespace="http://ltsc.ieee.org/xsd/imsccv1p3/LOM/resource")]
[System.Xml.Serialization.XmlRootAttribute("LOMType1")]
public partial class LOMType1
{
    
    #region Private fields
    private List<object> _items;
    
    private List<System.Xml.XmlAttribute> _anyAttr;
    #endregion
    
    public LOMType1()
    {
        this._anyAttr = new List<System.Xml.XmlAttribute>();
        this._items = new List<object>();
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("annotation", typeof(AnnotationType1))]
    [System.Xml.Serialization.XmlElementAttribute("classification", typeof(ClassificationType1))]
    [System.Xml.Serialization.XmlElementAttribute("educational", typeof(EducationalType1))]
    [System.Xml.Serialization.XmlElementAttribute("general", typeof(GeneralType1))]
    [System.Xml.Serialization.XmlElementAttribute("lifeCycle", typeof(LifeCycleType1))]
    [System.Xml.Serialization.XmlElementAttribute("metaMetadata", typeof(MetaMetadataType1))]
    [System.Xml.Serialization.XmlElementAttribute("relation", typeof(RelationType1))]
    [System.Xml.Serialization.XmlElementAttribute("rights", typeof(RightsType1))]
    [System.Xml.Serialization.XmlElementAttribute("technical", typeof(TechnicalType1))]
    public List<object> Items
    {
        get
        {
            return this._items;
        }
        set
        {
            this._items = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public List<System.Xml.XmlAttribute> AnyAttr
    {
        get
        {
            return this._anyAttr;
        }
        set
        {
            this._anyAttr = value;
        }
    }
}
}
#pragma warning restore
