// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.72
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace CommonCartridge.Core.Models.v1_3
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SetOfGUIDs.Type", Namespace="http://www.imsglobal.org/xsd/imsccv1p3/imscsmd_v1p0")]
[System.Xml.Serialization.XmlRootAttribute("SetOfGUIDsType")]
public partial class SetOfGUIDsType
{
    
    #region Private fields
    private List<LabelledGUIDType> _labelledGUID;
    
    private string _region;
    
    private string _version;
    #endregion
    
    public SetOfGUIDsType()
    {
        this._labelledGUID = new List<LabelledGUIDType>();
    }
    
    [System.Xml.Serialization.XmlElementAttribute("labelledGUID", ElementName="labelledGUID")]
    public List<LabelledGUIDType> LabelledGUID
    {
        get
        {
            return this._labelledGUID;
        }
        set
        {
            this._labelledGUID = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="region")]
    public string Region
    {
        get
        {
            return this._region;
        }
        set
        {
            this._region = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString", AttributeName="version")]
    public string Version
    {
        get
        {
            return this._version;
        }
        set
        {
            this._version = value;
        }
    }
}
}
#pragma warning restore
